# Generated by Django 6.0.1 on 2026-01-13 09:45

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField()),
                ('nacionalidad', models.CharField(max_length=100)),
                ('nacionalidad_es', models.CharField(max_length=100, null=True)),
                ('nacionalidad_en', models.CharField(max_length=100, null=True)),
                ('biografia', models.TextField()),
                ('biografia_es', models.TextField(null=True)),
                ('biografia_en', models.TextField(null=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('premios', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('nombre_es', models.CharField(max_length=200, null=True)),
                ('nombre_en', models.CharField(max_length=200, null=True)),
                ('direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('fecha_fundacion', models.DateField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalLibro',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('isbn', models.CharField(db_index=True, max_length=13)),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('numero_paginas', models.IntegerField(blank=True, null=True)),
                ('idioma', models.CharField(choices=[('ES', 'Español'), ('EN', 'Inglés')], default='ES', max_length=2)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, max_length=100, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('editorial', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='books.editorial')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical libro',
                'verbose_name_plural': 'historical libros',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('titulo_es', models.CharField(max_length=300, null=True)),
                ('titulo_en', models.CharField(max_length=300, null=True)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('numero_paginas', models.IntegerField(blank=True, null=True)),
                ('idioma', models.CharField(choices=[('ES', 'Español'), ('EN', 'Inglés')], default='ES', max_length=2)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('descripcion_es', models.TextField(blank=True, null=True)),
                ('descripcion_en', models.TextField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, max_length=100, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('autores', models.ManyToManyField(blank=True, to='books.autor')),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.editorial')),
            ],
        ),
    ]
