# Generated by Django 6.0.1 on 2026-01-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='is_out_of_stock',
            field=models.BooleanField(default=False, verbose_name='Está fuera de stock'),
        ),
        migrations.DeleteModel(
            name='HistoricalLibro',
        ),
    ]
