# Generated by Django 6.0.1 on 2026-01-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_libro_is_out_of_stock_delete_historicallibro'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorial',
            name='level',
            field=models.CharField(choices=[('1', 'Nivel 1'), ('2', 'Nivel 2'), ('3', 'Nivel 3')], default='1', max_length=2),
        ),
    ]
