# Generated by Django 4.2.11 on 2025-12-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_editorial_ciudad_alter_editorial_codigo_postal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='biografia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autor',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autor',
            name='premios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autor',
            name='sitio_web',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autor',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalautor',
            name='biografia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalautor',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalautor',
            name='premios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalautor',
            name='sitio_web',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalautor',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
